In [2]:
#import libraries
import pandas as pd
import numpy as np

In [4]:
#importing dataset
df = pd.read_csv("/Users/thotaruchitha/Downloads/Dataset.csv")

In [5]:
df.head()

,Country,Age,Salary,Purchased
0,India,38,68000.0,No
1,France,43,45000.0,Yes
2,Germany,30,54000.0,No
3,France,48,NaN,Yes
4,India,40,NaN,No


In [6]:
df.shape

(9, 4)

In [7]:
# Extracting independent variables
x=df.iloc[:,:-1].values

In [8]:
x

array([['India', 38, 68000.0],
       ['France', 43, 45000.0],
       ['Germany', 30, 54000.0],
       ['France', 48, nan],
       ['India', 40, nan],
       ['Germany', 35, 58000.0],
       ['France', 49, 79000.0],
       ['India', 50, 88000.0],
       ['Germany', 37, 77000.0]], dtype=object)

In [9]:
# Extracting dependent variables
y=df.iloc[:,-1].values

In [10]:
y

array(['No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'],
      dtype=object)

In [11]:
#handling missing values
from sklearn.impute import SimpleImputer

In [12]:
imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean')
x[:,1:3] = imputer.fit_transform(x[:,1:3])

In [13]:
x

array([['India', 38.0, 68000.0],
       ['France', 43.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['France', 48.0, 67000.0],
       ['India', 40.0, 67000.0],
       ['Germany', 35.0, 58000.0],
       ['France', 49.0, 79000.0],
       ['India', 50.0, 88000.0],
       ['Germany', 37.0, 77000.0]], dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Create a ColumnTransformer to apply OneHotEncoder to the first column
ct = ColumnTransformer(
    transformers=[('encode', OneHotEncoder(), [0])],
    remainder='passthrough'  # Keep the other columns as is
)

# Transform the data
x = ct.fit_transform(x)



In [15]:
x

array([[0.0, 0.0, 1.0, 38.0, 68000.0],
       [1.0, 0.0, 0.0, 43.0, 45000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 48.0, 67000.0],
       [0.0, 0.0, 1.0, 40.0, 67000.0],
       [0.0, 1.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 49.0, 79000.0],
       [0.0, 0.0, 1.0, 50.0, 88000.0],
       [0.0, 1.0, 0.0, 37.0, 77000.0]], dtype=object)

In [16]:
# splitting into train_test _split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split (x,y,test_size =0.2,random_state = 42)

In [17]:
x_train

array([[0.0, 1.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 68000.0],
       [0.0, 1.0, 0.0, 37.0, 77000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 40.0, 67000.0],
       [1.0, 0.0, 0.0, 48.0, 67000.0],
       [1.0, 0.0, 0.0, 49.0, 79000.0]], dtype=object)

In [18]:
#To perform feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [19]:
x_train

array([[-0.63245553,  1.15470054, -0.63245553, -0.72060376, -1.08740427],
       [-0.63245553, -0.8660254 ,  1.58113883, -0.24770754,  0.10194415],
       [-0.63245553,  1.15470054, -0.63245553, -0.40533961,  1.17235772],
       [-0.63245553,  1.15470054, -0.63245553, -1.50876412, -1.56314363],
       [-0.63245553, -0.8660254 ,  1.58113883,  0.0675566 , -0.01699069],
       [ 1.58113883, -0.8660254 , -0.63245553,  1.32861318, -0.01699069],
       [ 1.58113883, -0.8660254 , -0.63245553,  1.48624525,  1.41022741]])

In [20]:
x_test

array([[-0.63245553, -0.8660254 ,  1.58113883,  1.64387732,  2.48064098],
       [ 1.58113883, -0.8660254 , -0.63245553,  0.54045282, -2.63355721]])