In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("/Users/thotaruchitha/Downloads/Data.csv")

In [4]:
df.head()

,AT,V,AP,RH,PE
0,14.96,41.76,1024.07,73.17,463.26
1,25.18,62.96,1020.04,59.08,444.37
2,5.11,39.40,1012.16,92.14,488.56
3,20.86,57.32,1010.24,76.64,446.48
4,10.82,37.50,1009.23,96.62,473.90


In [5]:
df.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [6]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train , y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [8]:
#To perform feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [10]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
y_train = sc.fit_transform(y_train.reshape(-1, 1))

In [12]:
y_train

array([[-0.65133557],
       [ 2.1394232 ],
       [ 1.72827679],
       ...,
       [-1.13452046],
       [ 0.97802244],
       [ 1.05416066]])

In [13]:
from sklearn.tree import DecisionTreeRegressor

In [14]:
Regressor = DecisionTreeRegressor()
Regressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [16]:
y_pred = Regressor.predict(x_test)

In [17]:
y_pred

array([ 0.12527432, -1.10172245, -0.95998822, ...,  1.69079336,
       -1.47304272,  0.11238939])

In [19]:
# to invert the standardization transformation applied to the predicted values
y_pred = sc.inverse_transform(y_pred.reshape(-1,1))
y_pred

array([[456.57],
       [435.62],
       [438.04],
       ...,
       [483.3 ],
       [429.28],
       [456.35]])

In [23]:
from sklearn.metrics import r2_score
print(f'The r2 score is : {r2_score(y_test ,y_pred)}')

The r2 score is : 0.930722900633575
